version: 2
updates:
  # NPM dependencies for the MCP server
  - package-ecosystem: "npm"
    directory: "/mcp-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier*"
          - "vitest*"
          - "typescript*"
        update-types:
          - "minor"
          - "patch"
      # Group testing dependencies
      testing:
        patterns:
          - "*test*"
          - "*mock*"
          - "vitest*"
        update-types:
          - "minor"
          - "patch"
    # Separate production dependencies for careful review
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Security updates should be prioritized
    ignore:
      # Don't ignore any security updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        # Only for non-security updates
        

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      # Group all GitHub Actions updates
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
      
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/mcp-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
    # Only allow patch and minor updates for base images
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    # Review major version updates manually
    ignore:
      - dependency-name: "node"
        versions: ["21.x", "22.x", "23.x"]  # Stay on Node 20 LTS for now
        
  # Root package.json (if any)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "npm"
      - "root"
    commit-message:
      prefix: "deps"
      include: "scope"

# Security advisories configuration
# Dependabot will automatically create PRs for security updates
# regardless of the schedule