# Configuration for the GitHub labeler action
# https://github.com/actions/labeler

# Label based on file paths
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'
      - 'mcp-server/DOCS.md'
      - 'mcp-server/API.md'
      - 'mcp-server/README.md'

mcp-server:
  - changed-files:
    - any-glob-to-any-file:
      - 'mcp-server/**'
      - '!mcp-server/**.md'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.ts'
      - '**/*.test.js'
      - '**/__tests__/**'
      - '**/test/**'
      - 'vitest.config.ts'

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.github/dependabot.yml'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - '**/.dockerignore'
      - 'mcp-server/build.yaml'

home-assistant:
  - changed-files:
    - any-glob-to-any-file:
      - 'mcp-server/config.yaml'
      - 'mcp-server/apparmor.txt'
      - 'mcp-server/run.sh'
      - 'mcp-server/translations/**'

claude-extension:
  - changed-files:
    - any-glob-to-any-file:
      - 'claude-extension/**'
      - 'mcp-server/claude-extension/**'

security:
  - changed-files:
    - any-glob-to-any-file:
      - 'mcp-server/SECURITY.md'
      - 'mcp-server/apparmor.txt'
      - '.github/workflows/security.yaml'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - '**/package.json'
      - '**/package-lock.json'

typescript:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.ts'
      - '**/*.tsx'
      - 'tsconfig.json'
      - '**/tsconfig.json'

configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '.eslintrc.json'
      - '.prettierrc.json'
      - '.prettierignore'
      - '.gitignore'
      - 'repository.yaml'

breaking-change:
  - head-branch:
    - '^breaking/.*'
    - '^break/.*'

feature:
  - head-branch:
    - '^feature/.*'
    - '^feat/.*'

bug:
  - head-branch:
    - '^fix/.*'
    - '^bugfix/.*'
    - '^hotfix/.*'

enhancement:
  - head-branch:
    - '^enhance/.*'
    - '^improvement/.*'

refactor:
  - head-branch:
    - '^refactor/.*'
    - '^refactoring/.*'