name: MCP Server for Claude
version: 1.0.5
slug: mcp_claude
description: Control your smart home with Claude AI - bridges Claude Desktop to Home Assistant for natural language automation
url: https://github.com/mtebusi/HA_MCP
codenotary: matt@tebusi.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
homeassistant: 2024.10.0
hassio_api: true
homeassistant_api: true
auth_api: true
ports:
  6789/tcp: null
ports_description:
  6789/tcp: MCP Server HTTP/SSE endpoint for Claude Desktop
options:
  port: 6789
  connection_mode: sse
  authentication_required: true
  access_token: null
  log_level: info
  connection_timeout: 30
  max_clients: 5
  enable_entity_filtering: false
  allowed_domains: []
  blocked_entities: []
schema:
  port: "int(1024,65535)"
  connection_mode: list(sse|stdio)?
  authentication_required: bool
  access_token: "password?"
  log_level: list(debug|info|warning|error)
  connection_timeout: "int(5,300)"
  max_clients: "int(1,10)"
  enable_entity_filtering: bool
  allowed_domains:
    - "str?"
  blocked_entities:
    - "match(^[a-z0-9_]+\\.[a-z0-9_]+$)?"
image: "{arch}-addon-mcp-claude"
map:
  - homeassistant_config:ro
  - ssl:ro
  - addons:ro
  - backup:ro
  - share:ro
  - media:ro
panel_icon: mdi:robot
panel_title: MCP Claude
backup_exclude:
  - "*.log"
  - "*.cache"
  - "node_modules/"