name: Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  BUILD_ARGS: "--test"
  MONITORED_FILES: "build.yaml config.yaml Dockerfile run.sh"
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: dorny/paths-filter@v2
        with:
          filters: |
            mcp-server:
              - 'mcp-server/**'

      - name: Find add-on directories
        id: changed_addons
        run: |
          if [[ "${{ steps.changed_files.outputs.mcp-server }}" == "true" ]]; then
            echo "addons=[\"mcp-server\"]" >> $GITHUB_OUTPUT
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "addons=[]" >> $GITHUB_OUTPUT
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.changed == 'true'
    name: Build ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"

      - name: Check if add-on should be built
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "release" || "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "build=true" >> $GITHUB_OUTPUT
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      # Cache npm dependencies based on package-lock.json
      - name: Cache npm dependencies
        if: steps.check.outputs.build == 'true'
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: |
            ~/.npm
            ${{ matrix.addon }}/node_modules
          key: ${{ runner.os }}-npm-${{ matrix.addon }}-${{ hashFiles(format('{0}/package-lock.json', matrix.addon)) }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.addon }}-
            ${{ runner.os }}-npm-

      # Cache TypeScript build artifacts
      - name: Cache TypeScript build
        if: steps.check.outputs.build == 'true'
        uses: actions/cache@v4
        id: ts-cache
        with:
          path: ${{ matrix.addon }}/dist
          key: ${{ runner.os }}-tsbuild-${{ matrix.addon }}-${{ hashFiles(format('{0}/src/**/*.ts', matrix.addon), format('{0}/tsconfig.json', matrix.addon)) }}
          restore-keys: |
            ${{ runner.os }}-tsbuild-${{ matrix.addon }}-

      # Set up QEMU for multi-arch builds
      - name: Set up QEMU
        if: steps.check.outputs.build == 'true'
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx for advanced caching
      - name: Set up Docker Buildx
        if: steps.check.outputs.build == 'true'
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:master
            network=host

      # Cache Docker layers using GitHub Actions cache
      - name: Cache Docker layers
        if: steps.check.outputs.build == 'true'
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.addon }}-${{ hashFiles(format('{0}/Dockerfile', matrix.addon), format('{0}/build.yaml', matrix.addon)) }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.addon }}-
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: steps.check.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Test build ${{ matrix.addon }} add-on
        if: steps.check.outputs.build == 'true' && steps.check.outputs.push == 'false'
        timeout-minutes: 15
        uses: home-assistant/builder@master
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_INLINE_CACHE: 1
        with:
          args: |
            --test \
            --all \
            --target /data/${{ matrix.addon }} \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --image "{arch}-addon-mcp-claude"

      - name: Build and push ${{ matrix.addon }} add-on
        if: steps.check.outputs.build == 'true' && steps.check.outputs.push == 'true'
        timeout-minutes: 20
        uses: home-assistant/builder@master
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_INLINE_CACHE: 1
        with:
          args: |
            --push \
            --all \
            --target /data/${{ matrix.addon }} \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --image "{arch}-addon-mcp-claude"

      # Report cache effectiveness
      - name: Cache Performance Report
        if: always() && steps.check.outputs.build == 'true'
        run: |
          echo "## 📊 Cache Performance Report"
          echo "**Add-on:** ${{ matrix.addon }}"
          echo "**Build Type:** ${{ steps.check.outputs.push == 'true' && 'Release' || 'Test' }}"
          echo ""
          echo "### Cache Hit Status:"
          echo "- 📦 NPM Dependencies: ${{ steps.npm-cache.outputs.cache-hit == 'true' && '✅ HIT' || '❌ MISS' }}"
          echo "- 🔨 TypeScript Build: ${{ steps.ts-cache.outputs.cache-hit == 'true' && '✅ HIT' || '❌ MISS' }}"
          echo ""
          if [[ "${{ steps.npm-cache.outputs.cache-hit }}" == "true" && "${{ steps.ts-cache.outputs.cache-hit }}" == "true" ]]; then
            echo "🚀 **Optimal cache performance** - All caches hit!"
          elif [[ "${{ steps.npm-cache.outputs.cache-hit }}" == "true" || "${{ steps.ts-cache.outputs.cache-hit }}" == "true" ]]; then
            echo "⚡ **Partial cache hit** - Some acceleration achieved"
          else
            echo "🔄 **Full rebuild** - No cache hits (first build or significant changes)"
          fi