name: Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'mcp-server/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            base: ghcr.io/home-assistant/amd64-base:3.21
          - arch: aarch64
            platform: linux/arm64
            base: ghcr.io/home-assistant/aarch64-base:3.21
          - arch: armv7
            platform: linux/arm/v7
            base: ghcr.io/home-assistant/armv7-base:3.21
          - arch: armhf
            platform: linux/arm/v6
            base: ghcr.io/home-assistant/armhf-base:3.21
          - arch: i386
            platform: linux/386
            base: ghcr.io/home-assistant/i386-base:3.21
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version from config.yaml
        id: version
        run: |
          VERSION=$(grep "^version:" mcp-server/config.yaml | cut -d'"' -f2)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mcp-server
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BUILD_FROM=${{ matrix.base }}
          tags: |
            ${{ env.REGISTRY }}/mtebusi/${{ matrix.arch }}-addon-mcp-claude:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/mtebusi/${{ matrix.arch }}-addon-mcp-claude:latest
          labels: |
            org.opencontainers.image.title=MCP Server for Claude
            org.opencontainers.image.description=Model Context Protocol server for Claude AI integration with Home Assistant
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
            org.opencontainers.image.source=https://github.com/mtebusi/HA_MCP
            io.hass.arch=${{ matrix.arch }}
            io.hass.type=addon
            io.hass.version=${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/mtebusi/${{ matrix.arch }}-addon-mcp-claude:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/mtebusi/${{ matrix.arch }}-addon-mcp-claude:buildcache,mode=max
      
      - name: Verify image
        run: |
          echo "✅ Successfully built and pushed: ${{ env.REGISTRY }}/mtebusi/${{ matrix.arch }}-addon-mcp-claude:${{ steps.version.outputs.version }}"
          echo "Image is available at: https://github.com/mtebusi/HA_MCP/pkgs/container/${{ matrix.arch }}-addon-mcp-claude"