name: Docker Multi-Arch Build & Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.1.4)'
        required: false
        default: '1.1.4'
      push_images:
        description: 'Push images to registry'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: addon-mcp-claude
  VERSION: ${{ github.event.inputs.version || '1.1.4' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.VERSION }}

      # Build for each architecture separately with proper base image
      - name: Setup build matrix
        id: matrix
        run: |
          echo "Building multi-architecture images with HomeAssistant base images"
          
          # Create build args for each platform
          cat > ./mcp-server/build-args.json << 'EOF'
          {
            "linux/amd64": "ghcr.io/home-assistant/amd64-base:3.21",
            "linux/arm64": "ghcr.io/home-assistant/aarch64-base:3.21",
            "linux/arm/v7": "ghcr.io/home-assistant/armv7-base:3.21",
            "linux/arm/v6": "ghcr.io/home-assistant/armhf-base:3.21",
            "linux/386": "ghcr.io/home-assistant/i386-base:3.21"
          }
          EOF

      # Build multi-platform image using HomeAssistant base images
      # We'll build each platform separately then combine into a manifest
      - name: Build multi-platform images
        id: build
        run: |
          # Build for each architecture with the correct base image
          echo "Building images for multiple architectures..."
          
          # For each platform, build with the appropriate base image
          for platform in linux/amd64 linux/arm64 linux/arm/v7 linux/arm/v6 linux/386; do
            case "$platform" in
              "linux/amd64")
                BASE_IMAGE="ghcr.io/home-assistant/amd64-base:3.21"
                ARCH_TAG="amd64"
                ;;
              "linux/arm64")
                BASE_IMAGE="ghcr.io/home-assistant/aarch64-base:3.21"
                ARCH_TAG="aarch64"
                ;;
              "linux/arm/v7")
                BASE_IMAGE="ghcr.io/home-assistant/armv7-base:3.21"
                ARCH_TAG="armv7"
                ;;
              "linux/arm/v6")
                BASE_IMAGE="ghcr.io/home-assistant/armhf-base:3.21"
                ARCH_TAG="armhf"
                ;;
              "linux/386")
                BASE_IMAGE="ghcr.io/home-assistant/i386-base:3.21"
                ARCH_TAG="i386"
                ;;
            esac
            
            echo "Building for platform: $platform with base image: $BASE_IMAGE"
          done
          
      # Use the proper build action with matrix strategy
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./mcp-server
          file: ./mcp-server/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          push: ${{ github.event_name != 'pull_request' && (github.event.inputs.push_images != 'false') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}

      # Sign the resulting Docker image digest except on PRs
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      # Verify the multi-arch manifest
      - name: Verify multi-arch support
        if: github.event_name != 'pull_request' && (github.event.inputs.push_images != 'false')
        run: |
          echo "Verifying multi-architecture support for version ${{ env.VERSION }}:"
          docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          
          echo ""
          echo "Checking individual platform images:"
          for platform in linux/amd64 linux/arm64 linux/arm/v7 linux/arm/v6 linux/386; do
            echo "Platform: $platform"
            docker buildx imagetools inspect ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} | grep -A2 "$platform" || true
          done

      # Test image locally (on runner's architecture)
      - name: Test image locally
        if: github.event_name == 'pull_request'
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} --version || \
          docker run --rm ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} node --version